{% set name = "xicam.catalogviewer" %}
{% set version = "1.0.3" %}
{% set sha256 = "75fa707c943f0c03d1be99efd27509348b98d1c0ff29dbe9f1dd896cef169ddd" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/synchrotrons/Xi-cam.CatalogViewer/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: "python"
  script: "{{ PYTHON }} -m pip install . --no-deps -vv "

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - databroker
    - pyqt >=5

about:
  home: "https://github.com/synchrotrons/Xi-cam.CatalogViewer"
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The CAMERA platform for synchrotron data management, visualization, and reduction.
  description: |
    A light plugin for a simple view of catalog contents independent of technique.
